-- MySQL Script generated by MySQL Workbench
-- Sun Jan  9 19:12:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`tipousuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `token` VARCHAR(512) NOT NULL,
  `validado` TINYINT(1) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `id_tipousuario` INT NOT NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`empresa` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`paquete` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `fecha` DATETIME NOT NULL,
  `pagado` TINYINT(1) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_empresa` INT NOT NULL)
  
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `tipousuario`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `usuario`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `empresa`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `paquete`
  ADD PRIMARY KEY (`id`);



ALTER TABLE `tipousuario`
  MODIFY `id` bigint NOT NULL AUTO_INCREMENT;


ALTER TABLE `usuario`
  MODIFY `id` bigint NOT NULL AUTO_INCREMENT;

ALTER TABLE `empresa`
  MODIFY `id` bigint NOT NULL AUTO_INCREMENT;


ALTER TABLE `paquete`
  MODIFY `id` bigint NOT NULL AUTO_INCREMENT;


